[project]
name = "job_description"
version = "0.1.0"
description = "job_description using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<=3.13"
dependencies = [
    "crewai[tools]>=0.86.0,<1.0.0",
    "python-dotenv>=1.0.1",
    "streamlit>=1.40.2",
]

[project.scripts]
job_description = "job_description.main:run"
run_crew = "job_description.main:run"
train = "job_description.main:train"
replay = "job_description.main:replay"
test = "job_description.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
