analyze_company_profile:
  description: >
    Research and analyze company profile using website, domain {company_domain},
    and company name {company_name}. Highlight unique selling points and
    achievements that would attract potential candidates.
  expected_output: >
    A report containing: 
    1) Company culture and values assessment
    2) Key differentiators and achievements
    3) Recommendations for positioning the role in the market.

define_job_requirements:
  description: >
    Based on hiring manager {role} specifications and company analysis,
    create a detailed profile of the ideal candidate. Consider technical skills,
    experience level, cultural fit, and growth potential within the context of
    company goals and industry demands.
  expected_output: >
    A list of requirements for the ideal candidate.

write_job_posting:
  description: >
    Turn the company research and role requirements into a job posting.
    Incorporate benefits ({specific_benefits}).
  expected_output: >
    A ready-to-publish job posting for {role} at {company_name} and domain {company_domain}.
  output_file: >
    job_posting.md
